/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import asignarHorario.FacadeAsignarHorario;
import asignarHorario.IAsignarHorario;
import dto.DTOEmpleado;
import dto.DTOHorarioEmpleado;
import dto.DTOTurno;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Zaira
 */
public class Presentacion_gestionDeHorariosMenu extends javax.swing.JFrame {
    IAsignarHorario control = new FacadeAsignarHorario();
    /**
     * Creates new form GestionDeHorariosMain
     */
    public Presentacion_gestionDeHorariosMenu() {
        initComponents();
        generarTabla();
        setVisible(true);
    }

    /**
     * Método que llena la tabla con los empleados registrados.
     */
    public void generarTabla(){
        String[] columnas = {"Numéro de Empleado", "Nombre", "Apellidos"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0){
          @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }  
        };
        
        List<DTOEmpleado> empleados = control.recuperarEmpleados();
        for (DTOEmpleado e: empleados){
             Object[] fila = {
                 e.getId(),
                 e.getNombre(),
                 e.getApellidos()
             };
            modelo.addRow(fila);
        }
        
        tablaEmpleados.setModel(modelo);
        TableRowSorter<TableModel> buscador = new TableRowSorter<>(modelo);
        tablaEmpleados.setRowSorter(buscador);
        
        txtBuscar.addKeyListener(new KeyAdapter(){
            @Override
            public void keyReleased(KeyEvent e) {
                String busqueda = txtBuscar.getText();
                if (busqueda.isEmpty()) {
                    buscador.setRowFilter(null); 
                } else {
                    List<RowFilter<Object,Object>> filtros = new ArrayList<>(2);
                    filtros.add(RowFilter.regexFilter("(?i)" + busqueda, 1));
                    filtros.add(RowFilter.regexFilter("(?i)" + busqueda, 2));
                    
                    buscador.setRowFilter(RowFilter.orFilter(filtros));
                }
            }
        });
        
        accionAlSeleccionar();
    }

    
    /**
     * Método que obtiene al empleado que se desea editar y luego llama al método abrirVentana.
     */
    public void accionAlSeleccionar(){
        tablaEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent e) {
            if (e.getClickCount() == 2) {
                int fila = tablaEmpleados.getSelectedRow();
                
                if (fila != -1) {
                    try {
                        int filaModelo = tablaEmpleados.convertRowIndexToModel(fila);
                
                        Object valorId = tablaEmpleados.getModel().getValueAt(filaModelo, 0);
                        Long id = Long.valueOf(String.valueOf(valorId));
                        
                        abrirVentana(id);
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(
                            null, 
                            "Error al obtener el id del empleado", 
                            "Error", 
                            JOptionPane.ERROR_MESSAGE);
                            }
                }
            }
        }
    });
       
    }
    
    /**
     * Método que determina qué ventana debe abrir de acuerdo a si existen turnos registrados
     * Si existe al menos un turno, abre el gestor de horarios, en caso contrario, abre el
     * gestor de turnos.
     * @param id el id del empleado seleccionado
     */
    private void abrirVentana(Long id){
        DTOHorarioEmpleado horario = control.obtenerHorarioEmpleado(id);
        List<DTOTurno> turnos = control.recuperarTurno();
        if (turnos.isEmpty()){
            Presentacion_gestionDeTurnos gT = new Presentacion_gestionDeTurnos(id);
            gT.setVisible(true);
        } else {
            Presentacion_gestionDeHorarios gH = new Presentacion_gestionDeHorarios(id);
            gH.setVisible(true);
        }
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        lblBuscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seleccion De Empleado");
        setResizable(false);

        pnlFondo.setBackground(new java.awt.Color(39, 71, 125));

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setForeground(new java.awt.Color(51, 51, 51));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscar.setText("Buscar empleado:");

        tablaEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        tablaEmpleados.setForeground(new java.awt.Color(39, 71, 125));
        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaEmpleados);

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(lblBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
