/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import coordinador.Coordinador;

/**
 *
 * @author jesus
 */
public class Presentacion_menuGerente extends javax.swing.JFrame {

    Coordinador coordinador;

    public void setCoordinador(Coordinador coordinador) {
        this.coordinador = coordinador;
    }

    /**
     * Creates new form Presentacion_menuGerente
     */
    public Presentacion_menuGerente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenuGerente = new javax.swing.JPanel();
        btnRegistrarIncidencia = new javax.swing.JButton();
        btnGestionarTurno = new javax.swing.JButton();
        btnGestionarHorarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Gerente");

        pnlMenuGerente.setBackground(new java.awt.Color(39, 71, 125));

        btnRegistrarIncidencia.setBackground(new java.awt.Color(255, 166, 43));
        btnRegistrarIncidencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarIncidencia.setForeground(new java.awt.Color(39, 71, 125));
        btnRegistrarIncidencia.setText("Registrar Incidencia");

        btnGestionarTurno.setBackground(new java.awt.Color(255, 166, 43));
        btnGestionarTurno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGestionarTurno.setForeground(new java.awt.Color(39, 71, 125));
        btnGestionarTurno.setText("Gestionar Turnos");
        btnGestionarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarTurnoActionPerformed(evt);
            }
        });

        btnGestionarHorarios.setBackground(new java.awt.Color(255, 166, 43));
        btnGestionarHorarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGestionarHorarios.setForeground(new java.awt.Color(39, 71, 125));
        btnGestionarHorarios.setText("Gestionar Horarios");
        btnGestionarHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarHorariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuGerenteLayout = new javax.swing.GroupLayout(pnlMenuGerente);
        pnlMenuGerente.setLayout(pnlMenuGerenteLayout);
        pnlMenuGerenteLayout.setHorizontalGroup(
            pnlMenuGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuGerenteLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(pnlMenuGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGestionarTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMenuGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnRegistrarIncidencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGestionarHorarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(101, 101, 101))
        );
        pnlMenuGerenteLayout.setVerticalGroup(
            pnlMenuGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuGerenteLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnGestionarTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnGestionarHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnRegistrarIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenuGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenuGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarTurnoActionPerformed

    }//GEN-LAST:event_btnGestionarTurnoActionPerformed

    private void btnGestionarHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarHorariosActionPerformed

    }//GEN-LAST:event_btnGestionarHorariosActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestionarHorarios;
    private javax.swing.JButton btnGestionarTurno;
    private javax.swing.JButton btnRegistrarIncidencia;
    private javax.swing.JPanel pnlMenuGerente;
    // End of variables declaration//GEN-END:variables
}
