/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import coordinador.Coordinador;
import dto.DTOEmpleado;
import dto.DTORegistroMarca;
import java.awt.event.ActionEvent;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import objetosNegocio.NegocioException;

/**
 *
 * @author josma
 */
public class Presentacion_registrarAsistencia extends javax.swing.JFrame {
    private DTOEmpleado empleado; //Empleado que ya viene desde la tabla 
    Coordinador coordinador; //Coordiandor
    
    /**
     * Creates new form Presentacion_registrarAsistencia
     */
    public Presentacion_registrarAsistencia(DTOEmpleado empleado, Coordinador coordinador) {
        initComponents();
        this.coordinador = coordinador;
        this.empleado = empleado; 
        setVisible(true);
        configurarPantalla();
    }
    
    private void configurarPantalla(){
        //1.Cambiar la etiqueta al nombre del usuario
        lblEmpleadoNombre.setText(empleado.getNombre());
        //2.Hacer una consulta para poder cambiar el texto del bóton
        try{
            DTORegistroMarca marcaHoy = coordinador.gestionAsistencias.obtenerMarca(empleado.getId(), LocalDate.now());
            
            if (marcaHoy == null) {
                btnRegistrar.setText("RegistrarEntrada");
            }else if(marcaHoy.getSalida() == null){
                btnRegistrar.setText("Registrar Salida");
            }else{
                btnRegistrar.setText("Jornada terminada");
                btnRegistrar.setEnabled(false);
            }
        }catch(NegocioException e){
            JOptionPane.showMessageDialog(this, "Error al consultar el estado: " + e.getMessage());
        }
        
    }
    
    private void btnRegistrarActionPerformed(ActionEvent evt){
        try{
            DTORegistroMarca dtoRegistro = new DTORegistroMarca();
            dtoRegistro.setEmpleadoDTO(this.empleado);
            coordinador.gestionAsistencias.crearMarca(dtoRegistro);
            JOptionPane.showMessageDialog(this, "Marca registrada con éxito");
            configurarPantalla();
        }catch(NegocioException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error de validación", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void btnRegresarActionPerformed(ActionEvent evt){
        coordinador.cambioDeVentana(coordinador.MENU_PRINCIPAL);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblBienvenida = new javax.swing.JLabel();
        lblEmpleadoNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panPrincipal.setBackground(new java.awt.Color(39, 71, 125));

        btnRegistrar.setBackground(new java.awt.Color(255, 166, 43));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(39, 71, 125));
        btnRegistrar.setText("Registrar");

        btnRegresar.setBackground(new java.awt.Color(224, 30, 72));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");

        lblBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenida.setText("Bienvenido");

        lblEmpleadoNombre.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblEmpleadoNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpleadoNombre.setText("lblNombre");

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegresar))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblEmpleadoNombre)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresar)
                .addGap(119, 119, 119)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBienvenida)
                    .addComponent(lblEmpleadoNombre))
                .addGap(86, 86, 86)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblEmpleadoNombre;
    private javax.swing.JPanel panPrincipal;
    // End of variables declaration//GEN-END:variables
}
