/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import coordinador.Coordinador;
import dto.DTOEmpleado;
import dto.DTOIncidencia;
import gestionIncidencias.FacadeGestionIncidencias;
import gestionIncidencias.IGestionIncidencias;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import objetosNegocio.NegocioException;

/**
 *
 * @author jesus
 */
public class Presentacion_registroDeIncidencias extends javax.swing.JFrame {

    private IGestionIncidencias control = new FacadeGestionIncidencias();

    private DTOEmpleado empleado;

    private Coordinador coordinador;

    public void setCoordinador(Coordinador coordinador) {

        this.coordinador = coordinador;
    }

    /**
     * Creates new customizer Presentacion_gestionDeIncidenciasMenu
     */
    public Presentacion_registroDeIncidencias() {

        initComponents();
        comboTipos.setModel(new DefaultComboBoxModel<>(DTOIncidencia.TiposIncidencia.values()));

    }

    public void cargarTexto(DTOEmpleado empleado) {

        this.empleado = empleado;

        fieldEmpleado.setText(empleado.getNombre() + " " + empleado.getApellidoPaterno() + " " + empleado.getApellidoMaterno());
    }

    ;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistorIncidencias = new javax.swing.JPanel();
        jLabelMenu = new javax.swing.JLabel();
        labelEmpleado = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        fieldEmpleado = new javax.swing.JTextField();
        fieldDescripcion = new javax.swing.JTextField();
        botonRegistrarIncidencia = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        labelDescripcion = new javax.swing.JLabel();
        comboTipos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de incidencias");
        setResizable(false);

        pnlRegistorIncidencias.setBackground(new java.awt.Color(39, 71, 125));

        jLabelMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelMenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMenu.setText("Registro de Incidencias");

        labelEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        labelEmpleado.setText("Empleado:");

        labelTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTipo.setForeground(new java.awt.Color(255, 255, 255));
        labelTipo.setText("Tipo:");

        fieldEmpleado.setEditable(false);
        fieldEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        fieldEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        fieldEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEmpleadoActionPerformed(evt);
            }
        });

        fieldDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        fieldDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        fieldDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDescripcionActionPerformed(evt);
            }
        });

        botonRegistrarIncidencia.setBackground(new java.awt.Color(255, 153, 0));
        botonRegistrarIncidencia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonRegistrarIncidencia.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrarIncidencia.setText("Registrar Incidencia");
        botonRegistrarIncidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarIncidenciaActionPerformed(evt);
            }
        });

        botonCancelar.setBackground(new java.awt.Color(224, 30, 72));
        botonCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        labelDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        labelDescripcion.setText("Descripción:");

        comboTipos.setBackground(new java.awt.Color(255, 255, 255));
        comboTipos.setForeground(new java.awt.Color(0, 0, 0));
        comboTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTiposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistorIncidenciasLayout = new javax.swing.GroupLayout(pnlRegistorIncidencias);
        pnlRegistorIncidencias.setLayout(pnlRegistorIncidenciasLayout);
        pnlRegistorIncidenciasLayout.setHorizontalGroup(
            pnlRegistorIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistorIncidenciasLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(pnlRegistorIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegistorIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldEmpleado)
                    .addComponent(comboTipos, 0, 273, Short.MAX_VALUE)
                    .addComponent(fieldDescripcion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistorIncidenciasLayout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addGroup(pnlRegistorIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistorIncidenciasLayout.createSequentialGroup()
                        .addComponent(botonRegistrarIncidencia)
                        .addGap(18, 18, 18)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistorIncidenciasLayout.createSequentialGroup()
                        .addComponent(jLabelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))))
        );
        pnlRegistorIncidenciasLayout.setVerticalGroup(
            pnlRegistorIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistorIncidenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMenu)
                .addGap(55, 55, 55)
                .addGroup(pnlRegistorIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmpleado)
                    .addComponent(fieldEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlRegistorIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipo)
                    .addComponent(comboTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(pnlRegistorIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescripcion)
                    .addComponent(fieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(pnlRegistorIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegistrarIncidencia)
                    .addComponent(botonCancelar))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlRegistorIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlRegistorIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEmpleadoActionPerformed

    private void fieldDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDescripcionActionPerformed

    private void botonRegistrarIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarIncidenciaActionPerformed

        boolean validacion = validarFormulario();

        if (validacion) {

            DTOIncidencia incidencia = new DTOIncidencia((DTOIncidencia.TiposIncidencia) comboTipos.getSelectedItem(), empleado, fieldDescripcion.getText());

            incidencia.setFecha(LocalDate.now());
            incidencia.setEstado(DTOIncidencia.Estado.PENDIENTE);
            incidencia.setObservaciones("");

            try {

                int opcion = JOptionPane.showConfirmDialog(this, "¿Está seguro de registrar esta incidencia?", "Confirmaciön", JOptionPane.YES_NO_OPTION);

                if (opcion == 0) {

                    control.crearIncidencia(incidencia);
                    control.enviarSupervisor();
                    JOptionPane.showMessageDialog(this, "Incidencia Registrada");

                } else {

                    JOptionPane.showMessageDialog(this, "La incidencia no ha sido registrada");

                }

            } catch (NegocioException ex) {

                JOptionPane.showMessageDialog(
                        this,
                        "Error al registrar la incidencia: " + ex.getMessage(),
                        "Error al registrar.",
                        JOptionPane.ERROR_MESSAGE);

            }

        }

    }//GEN-LAST:event_botonRegistrarIncidenciaActionPerformed

    private void comboTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTiposActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed

        coordinador.cambioDeVentana(Coordinador.LISTA_DE_EMPLEADOS);
        this.dispose();

    }//GEN-LAST:event_botonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRegistrarIncidencia;
    private javax.swing.JComboBox<DTOIncidencia.TiposIncidencia> comboTipos;
    private javax.swing.JTextField fieldDescripcion;
    private javax.swing.JTextField fieldEmpleado;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelEmpleado;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JPanel pnlRegistorIncidencias;
    // End of variables declaration//GEN-END:variables

    private boolean validarFormulario() {

        if (fieldDescripcion.getText().isBlank()) {

            JOptionPane.showMessageDialog(this,
                    "La descripción no puede estar vacía",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

            return false;

        }

        return true;

    }

}
