/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import coordinador.Coordinador;
import dto.DTOEmpleado;
import dto.DTOIncidencia;
import gestionIncidencias.FacadeGestionIncidencias;
import gestionIncidencias.IGestionIncidencias;
import java.awt.Color;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import objetosNegocio.NegocioException;

/**
 *
 * @author Zaira
 */
public class Presentacion_validacionIncidenciasTabla extends javax.swing.JFrame {

    DefaultTableModel modeloTablaIncidencias;
    IGestionIncidencias control = new FacadeGestionIncidencias();
    String rdbtnSeleccionado;

    Coordinador coordinador;

    /**
     * Creates new form Presentacion_gestionDeIncidenciasMenuPrincipal
     */
    public Presentacion_validacionIncidenciasTabla(Coordinador coordinador) {
        this.coordinador = coordinador;
        initComponents();
        configuracionBotones();
        crearTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlIncidencias = new javax.swing.JPanel();
        panelEncabezado = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        pnlScroll = new javax.swing.JScrollPane();
        tablaIncidencias = new javax.swing.JTable();
        cmbTipoIncidencia = new javax.swing.JComboBox<>();
        txtBuscarEmpleado = new javax.swing.JTextField();
        rdbtnPendiente = new javax.swing.JRadioButton();
        rdbtnRechazada = new javax.swing.JRadioButton();
        lblEmpleado = new javax.swing.JLabel();
        rdbtnValidada = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlIncidencias.setBackground(new java.awt.Color(255, 255, 255));

        panelEncabezado.setBackground(new java.awt.Color(39, 71, 125));

        btnRegresar.setBackground(new java.awt.Color(224, 30, 72));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");

        javax.swing.GroupLayout panelEncabezadoLayout = new javax.swing.GroupLayout(panelEncabezado);
        panelEncabezado.setLayout(panelEncabezadoLayout);
        panelEncabezadoLayout.setHorizontalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(545, Short.MAX_VALUE))
        );
        panelEncabezadoLayout.setVerticalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEncabezadoLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(37, 37, 37))
        );

        tablaIncidencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pnlScroll.setViewportView(tablaIncidencias);

        cmbTipoIncidencia.setBackground(new java.awt.Color(255, 255, 255));
        cmbTipoIncidencia.setForeground(new java.awt.Color(51, 51, 51));
        cmbTipoIncidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoIncidenciaActionPerformed(evt);
            }
        });

        txtBuscarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscarEmpleado.setForeground(new java.awt.Color(51, 51, 51));

        rdbtnPendiente.setForeground(new java.awt.Color(51, 51, 51));
        rdbtnPendiente.setText("Pendiente");

        rdbtnRechazada.setForeground(new java.awt.Color(51, 51, 51));
        rdbtnRechazada.setText("Rechazada");

        lblEmpleado.setForeground(new java.awt.Color(51, 51, 51));
        lblEmpleado.setText("Empleado:");

        rdbtnValidada.setForeground(new java.awt.Color(51, 51, 51));
        rdbtnValidada.setText("Validada");

        javax.swing.GroupLayout pnlIncidenciasLayout = new javax.swing.GroupLayout(pnlIncidencias);
        pnlIncidencias.setLayout(pnlIncidenciasLayout);
        pnlIncidenciasLayout.setHorizontalGroup(
            pnlIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIncidenciasLayout.createSequentialGroup()
                .addComponent(panelEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlIncidenciasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIncidenciasLayout.createSequentialGroup()
                        .addComponent(rdbtnPendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbtnValidada, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbtnRechazada, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(lblEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIncidenciasLayout.createSequentialGroup()
                        .addComponent(cmbTipoIncidencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(135, 135, 135)
                        .addComponent(txtBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlScroll, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlIncidenciasLayout.setVerticalGroup(
            pnlIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIncidenciasLayout.createSequentialGroup()
                .addComponent(panelEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIncidenciasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbtnPendiente)
                            .addComponent(rdbtnRechazada)
                            .addComponent(rdbtnValidada))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIncidenciasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEmpleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbTipoIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, 649, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoIncidenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoIncidenciaActionPerformed

    public void crearTabla() {
        String[] columnas = {"Id Incidencia", "Id Empleado", "Nombre", "Apellido Paterno", "Apellido Materno", "Tipo", "Fecha", "Estado"};
        modeloTablaIncidencias = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        try {
            Set<String> tipos = new HashSet<>();
            String filtro = (rdbtnSeleccionado != null) ? rdbtnSeleccionado : "PENDIENTE";
            List<DTOIncidencia> incidencias = control.obtenerIncidencias(filtro);
            for (DTOIncidencia i : incidencias) {
                DTOEmpleado empleado = i.getEmpleado();
                tipos.add(i.getTipo().toString());
                String nombre = (empleado != null && empleado.getNombre() != null) ? empleado.getNombre() : "N/A";
                String apePaterno = (empleado != null && empleado.getApellidoPaterno() != null) ? empleado.getApellidoPaterno() : "";
                String apeMaterno = (empleado != null && empleado.getApellidoMaterno() != null) ? empleado.getApellidoMaterno() : "";
                Object[] fila = {
                    i.getIdIncidencia(),
                    empleado.getId(),
                    nombre,
                    apePaterno,
                    apeMaterno,
                    i.getTipo(),
                    i.getFecha(),
                    i.getEstado().name()
                };
                modeloTablaIncidencias.addRow(fila);
            }

            configurarComboBox(tipos);

            tablaIncidencias.setModel(modeloTablaIncidencias);
            tablaIncidencias.getColumnModel().getColumn(0).setMinWidth(0);
            tablaIncidencias.getColumnModel().getColumn(0).setPreferredWidth(0);
            tablaIncidencias.getColumnModel().getColumn(0).setMaxWidth(0);
            tablaIncidencias.getColumnModel().getColumn(0).setResizable(false);
            
            tablaIncidencias.getColumnModel().getColumn(1).setMinWidth(0);
            tablaIncidencias.getColumnModel().getColumn(1).setPreferredWidth(0);
            tablaIncidencias.getColumnModel().getColumn(1).setMaxWidth(0);
            tablaIncidencias.getColumnModel().getColumn(1).setResizable(false);
            
            TableRowSorter<TableModel> buscador = new TableRowSorter<>(modeloTablaIncidencias);
            tablaIncidencias.setRowSorter(buscador);

            txtBuscarEmpleado.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) {
                    busquedaPorFiltros(buscador);
                }
            });

            cmbTipoIncidencia.addActionListener(e -> busquedaPorFiltros(buscador));
            rdbtnPendiente.addActionListener(e -> {
                this.rdbtnSeleccionado = "PENDIENTE";
                crearTabla();
            });
            rdbtnValidada.addActionListener(e -> {
                this.rdbtnSeleccionado = "VALIDADA";
                crearTabla();
            });
            rdbtnRechazada.addActionListener(e -> {
                this.rdbtnSeleccionado = "RECHAZADA";
                crearTabla();
            });
            busquedaPorFiltros(buscador);

            tablaIncidencias.getColumnModel().getColumn(7).setCellRenderer(new RenderizadorEstado());
            tablaIncidencias.setRowHeight(60);
            accionAlSeleccionar();

        } catch (NegocioException ex) {

        }

    }

    public void configuracionBotones() {
        ButtonGroup grupoTurnos = new ButtonGroup();

        grupoTurnos.add(rdbtnPendiente);
        grupoTurnos.add(rdbtnValidada);
        grupoTurnos.add(rdbtnRechazada);

        rdbtnPendiente.setSelected(true);
        
        rdbtnSeleccionado = "PENDIENTE";
    }

    public void configurarComboBox(Set<String> tipos) {
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        modelo.addElement("Todos");
        modelo.addAll(tipos);
        cmbTipoIncidencia.setModel(modelo);
    }

    public void busquedaPorFiltros(TableRowSorter<TableModel> buscador) {
        List<RowFilter<Object, Object>> filtrosConjuntos = new ArrayList<>();
        String busqueda = txtBuscarEmpleado.getText().trim();

        if (!busqueda.isEmpty()) {
            List<RowFilter<Object, Object>> filtroPorEmpleado = new ArrayList<>();
            filtroPorEmpleado.add(RowFilter.regexFilter("(?i)" + busqueda, 2));
            filtroPorEmpleado.add(RowFilter.regexFilter("(?i)" + busqueda, 3));
            filtroPorEmpleado.add(RowFilter.regexFilter("(?i)" + busqueda, 4));
            filtrosConjuntos.add(RowFilter.orFilter(filtroPorEmpleado));
        }

        String tipoSeleccionado = (String) cmbTipoIncidencia.getSelectedItem();
        if (tipoSeleccionado != null && !tipoSeleccionado.equals("Todos")) {
            filtrosConjuntos.add(RowFilter.regexFilter("^" + tipoSeleccionado + "$", 5));
        }

//        String estadoSeleccionado = "";
//        if (rdbtnPendiente.isSelected()) {
//            estadoSeleccionado = "PENDIENTE";
//        } else if (rdbtnValidada.isSelected()) {
//            estadoSeleccionado = "VALIDADA";
//        } else if (rdbtnRechazada.isSelected()) {
//            estadoSeleccionado = "RECHAZADA";
//        }
//
//        this.rdbtnSeleccionado = estadoSeleccionado;
//
//        if (!estadoSeleccionado.isEmpty()) {
//            filtrosConjuntos.add(RowFilter.regexFilter("^" + estadoSeleccionado + "$", 7));
//        }

        if (filtrosConjuntos.isEmpty()) {
            buscador.setRowFilter(null);
        } else {
            buscador.setRowFilter(RowFilter.andFilter(filtrosConjuntos));
        }
    }

    private class RenderizadorEstado extends JPanel implements TableCellRenderer {

        private final JButton btnEstado;

        public RenderizadorEstado() {
            this.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 2));
            this.setOpaque(true);

            this.btnEstado = new JButton();
            this.add(btnEstado);
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {

            if (value != null) {
                btnEstado.setText(value.toString());

                if (value.toString().equals("PENDIENTE")) {
                    btnEstado.setBackground(Color.YELLOW);
                } else if (value.toString().equals("VALIDADA")) {
                    btnEstado.setBackground(Color.GREEN);
                } else if (value.toString().equals("RECHAZADA")) {
                    btnEstado.setBackground(Color.RED);
                }
            }

            if (isSelected) {
                this.setBackground(table.getSelectionBackground());
            } else {
                this.setBackground(table.getBackground());
            }

            return this;
        }
    }

   public void accionAlSeleccionar(){
       tablaIncidencias.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int fila = tablaIncidencias.getSelectedRow();

                    if (fila != -1) {
                            int filaModelo = tablaIncidencias.convertRowIndexToModel(fila);
                            String id = tablaIncidencias.getValueAt(filaModelo, 0).toString();
                            String idEmpleado = tablaIncidencias.getValueAt(filaModelo, 1).toString();
                            String nombre = tablaIncidencias.getValueAt(filaModelo, 2).toString();
                            String apellidoP = tablaIncidencias.getValueAt(filaModelo, 3).toString();
                            String apellidoM = tablaIncidencias.getValueAt(filaModelo, 4).toString();
                            String tipo = tablaIncidencias.getValueAt(filaModelo, 5).toString();
                            try {
                                LocalDate fecha = LocalDate.parse(tablaIncidencias.getValueAt(filaModelo, 6).toString());
                           
                            DTOIncidencia.TiposIncidencia tipoIncidencia = DTOIncidencia.TiposIncidencia.AUSENTISMO;
                            for (DTOIncidencia.TiposIncidencia i: DTOIncidencia.TiposIncidencia.values()){
                                if (tipo.toUpperCase().contains(i.name())){
                                    tipoIncidencia = i;
                                }
                            }
                            
                            DTOIncidencia incidenciaValidar = new DTOIncidencia();
                            DTOEmpleado empleado = new DTOEmpleado();
                            empleado.setId(idEmpleado);
                            empleado.setNombre(nombre);
                            empleado.setApellidoMaterno(apellidoM);
                            empleado.setApellidoPaterno(apellidoP);
                            incidenciaValidar.setIdIncidencia(id);
                            incidenciaValidar.setEmpleado(empleado);
                            incidenciaValidar.setTipo(tipoIncidencia);
                            incidenciaValidar.setFecha(fecha);
                            
                            
                            

                            incidenciaValidar = coordinador.cambioDeVentana(Coordinador.VALIDACION_DE_INCIDENCIAS, incidenciaValidar);
                            
                            
                            if (incidenciaValidar.getEstado().equals(DTOIncidencia.Estado.VALIDADA)){
                                control.validarIncidencia(incidenciaValidar);
                            } else {
                                control.rechazarIncidencia(incidenciaValidar);
                            }
                                
                                crearTabla();
                            } catch (NegocioException ex){
                                JOptionPane.showMessageDialog(
                                    null,
                                    "Error al validar la incidencia: " + ex.getMessage(),
                                    "Error.",
                                    JOptionPane.ERROR_MESSAGE);
                            } catch (DateTimeParseException ex){
                                JOptionPane.showMessageDialog(
                                    null,
                                    "Error al recuperar la fecha de la incidencia: " + ex.getMessage(),
                                    "Error.",
                                    JOptionPane.ERROR_MESSAGE);
                            }
                    }
                }
            }
       });
        
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbTipoIncidencia;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JPanel panelEncabezado;
    private javax.swing.JPanel pnlIncidencias;
    private javax.swing.JScrollPane pnlScroll;
    private javax.swing.JRadioButton rdbtnPendiente;
    private javax.swing.JRadioButton rdbtnRechazada;
    private javax.swing.JRadioButton rdbtnValidada;
    private javax.swing.JTable tablaIncidencias;
    private javax.swing.JTextField txtBuscarEmpleado;
    // End of variables declaration//GEN-END:variables
}
