/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import coordinador.Coordinador;

/**
 *
 * @author jesus
 */
public class Presentacion_menuGerente extends javax.swing.JFrame {

    Coordinador coordinador;

    /**
     * Creates new form Presentacion_menuGerente
     */
    public Presentacion_menuGerente(Coordinador coordinador) {
        this.coordinador = coordinador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGestionarTurno1 = new javax.swing.JButton();
        pnlMenuGerente = new javax.swing.JPanel();
        btnRegistrarIncidencia = new javax.swing.JButton();
        btnRegistrarEmpleado = new javax.swing.JButton();
        btnGestionarHorarios = new javax.swing.JButton();
        btnGestionarTurno = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();

        btnGestionarTurno1.setBackground(new java.awt.Color(255, 166, 43));
        btnGestionarTurno1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGestionarTurno1.setForeground(new java.awt.Color(39, 71, 125));
        btnGestionarTurno1.setText("Gestionar Turnos");
        btnGestionarTurno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarTurno1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Gerente");

        pnlMenuGerente.setBackground(new java.awt.Color(39, 71, 125));

        btnRegistrarIncidencia.setBackground(new java.awt.Color(255, 166, 43));
        btnRegistrarIncidencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarIncidencia.setForeground(new java.awt.Color(39, 71, 125));
        btnRegistrarIncidencia.setText("Registrar Incidencia");
        btnRegistrarIncidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarIncidenciaActionPerformed(evt);
            }
        });

        btnRegistrarEmpleado.setBackground(new java.awt.Color(255, 166, 43));
        btnRegistrarEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarEmpleado.setForeground(new java.awt.Color(39, 71, 125));
        btnRegistrarEmpleado.setText("Registrar Empleado");
        btnRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEmpleadoActionPerformed(evt);
            }
        });

        btnGestionarHorarios.setBackground(new java.awt.Color(255, 166, 43));
        btnGestionarHorarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGestionarHorarios.setForeground(new java.awt.Color(39, 71, 125));
        btnGestionarHorarios.setText("Gestionar Horarios");
        btnGestionarHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarHorariosActionPerformed(evt);
            }
        });

        btnGestionarTurno.setBackground(new java.awt.Color(255, 166, 43));
        btnGestionarTurno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGestionarTurno.setForeground(new java.awt.Color(39, 71, 125));
        btnGestionarTurno.setText("Gestionar Turnos");
        btnGestionarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarTurnoActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(255, 51, 0));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnReporte.setBackground(new java.awt.Color(255, 166, 43));
        btnReporte.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReporte.setForeground(new java.awt.Color(39, 71, 125));
        btnReporte.setText("Reporte Asistencia");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuGerenteLayout = new javax.swing.GroupLayout(pnlMenuGerente);
        pnlMenuGerente.setLayout(pnlMenuGerenteLayout);
        pnlMenuGerenteLayout.setHorizontalGroup(
            pnlMenuGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuGerenteLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuGerenteLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(pnlMenuGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarIncidencia)
                    .addComponent(btnRegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionarHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionarTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        pnlMenuGerenteLayout.setVerticalGroup(
            pnlMenuGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuGerenteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addGap(20, 20, 20)
                .addComponent(btnRegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGestionarTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGestionarHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenuGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenuGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEmpleadoActionPerformed
        coordinador.cambioDeVentana(Coordinador.CONTRATACION_EMPLEADO);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarEmpleadoActionPerformed

    private void btnGestionarHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarHorariosActionPerformed

        coordinador.cambioDeVentana(Coordinador.LISTA_DE_EMPLEADOS);
        coordinador.setVentanaSiguiente(Coordinador.GESTION_DE_HORARIOS);
        this.dispose();

    }//GEN-LAST:event_btnGestionarHorariosActionPerformed

    private void btnGestionarTurno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarTurno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarTurno1ActionPerformed

    private void btnGestionarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarTurnoActionPerformed
        coordinador.cambioDeVentana(Coordinador.GESTION_DE_TURNOS);
        this.dispose();
    }//GEN-LAST:event_btnGestionarTurnoActionPerformed

    private void btnRegistrarIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarIncidenciaActionPerformed

        coordinador.cambioDeVentana(Coordinador.LISTA_DE_EMPLEADOS);
        coordinador.setVentanaSiguiente(Coordinador.REGISTRO_DE_INCIDENCIAS);
        this.dispose();

    }//GEN-LAST:event_btnRegistrarIncidenciaActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:

        coordinador.cambioDeVentana(Coordinador.MENU_PRINCIPAL);
        this.dispose();

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:      
        coordinador.cambioDeVentana(Coordinador.LISTA_DE_EMPLEADOS);
        coordinador.setVentanaSiguiente(Coordinador.REPORTE_ASISTENCIA);
        this.dispose();
    }//GEN-LAST:event_btnReporteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestionarHorarios;
    private javax.swing.JButton btnGestionarTurno;
    private javax.swing.JButton btnGestionarTurno1;
    private javax.swing.JButton btnRegistrarEmpleado;
    private javax.swing.JButton btnRegistrarIncidencia;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnReporte;
    private javax.swing.JPanel pnlMenuGerente;
    // End of variables declaration//GEN-END:variables
}
