<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>itson</groupId>
        <artifactId>proyecto_LosInges</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <artifactId>infraestructura_Mensajeria</artifactId>
    <packaging>jar</packaging>
    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>DTO_Negocios</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>jakarta.mail</artifactId>
            <version>2.0.1</version>
        </dependency>
        <dependency>
            <groupId>jakarta.mail</groupId>
            <artifactId>jakarta.mail-api</artifactId>
            <version>2.1.3</version>
            <type>jar</type>
        </dependency>
    </dependencies>
    
    <properties>
        <maven.compiler.release>23</maven.compiler.release>
        <exec.mainClass>itson.infraestructura_mensajeria.Infraestructura_Mensajeria</exec.mainClass>
    </properties>
</project>