/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.presentacion;

import dto.DTOTurno;
import java.awt.Color;
import java.awt.Component;
import java.time.DayOfWeek;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import javax.swing.JCheckBox;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zaira
 */
public class GestionDeTurnos extends javax.swing.JFrame {
    DefaultTableModel modeloTabla = new DefaultTableModel();
    Map<JCheckBox, DayOfWeek> mapaDias = new HashMap<>();
    Color colorTurno;
    /**
     * Creates new form GestionDeHorarios
     */
    public GestionDeTurnos() {
        initComponents();
        configurarSpinners();
        configurarDias();
        configurarTabla();
        tablaTurnosDisponibles.getColumnModel().getColumn(4).setCellRenderer(new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, 
            boolean isSelected, boolean hasFocus, int row, int column) {

            Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            if (value instanceof Color) {
                Color colorEvento = (Color) value;
                c.setBackground(colorEvento);
                c.setForeground(colorEvento);
            }
            return c;
            }
        });
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGestionTurno = new javax.swing.JPanel();
        pnlScroll = new javax.swing.JScrollPane();
        tablaTurnosDisponibles = new javax.swing.JTable();
        pnlFormularioTurno = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblHoraInicio = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        spnHoraInicio = new javax.swing.JSpinner();
        lblHoraFin = new javax.swing.JLabel();
        spnHoraFin = new javax.swing.JSpinner();
        lblDias = new javax.swing.JLabel();
        chkLunes = new javax.swing.JCheckBox();
        chkMiercoles = new javax.swing.JCheckBox();
        chkMartes = new javax.swing.JCheckBox();
        chkJueves = new javax.swing.JCheckBox();
        chkViernes = new javax.swing.JCheckBox();
        chkSabado = new javax.swing.JCheckBox();
        chkDomingo = new javax.swing.JCheckBox();
        btnColor = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión De Turno");
        setResizable(false);

        pnlGestionTurno.setBackground(new java.awt.Color(255, 255, 255));

        pnlScroll.setBackground(new java.awt.Color(255, 255, 255));
        pnlScroll.setForeground(new java.awt.Color(4, 45, 98));

        tablaTurnosDisponibles.setBackground(new java.awt.Color(255, 255, 255));
        tablaTurnosDisponibles.setForeground(new java.awt.Color(4, 45, 98));
        tablaTurnosDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Hora Inicio", "Hora Fin", "Días"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        pnlScroll.setViewportView(tablaTurnosDisponibles);
        if (tablaTurnosDisponibles.getColumnModel().getColumnCount() > 0) {
            tablaTurnosDisponibles.getColumnModel().getColumn(0).setResizable(false);
            tablaTurnosDisponibles.getColumnModel().getColumn(1).setResizable(false);
            tablaTurnosDisponibles.getColumnModel().getColumn(2).setResizable(false);
            tablaTurnosDisponibles.getColumnModel().getColumn(3).setResizable(false);
        }

        pnlFormularioTurno.setBackground(new java.awt.Color(39, 71, 125));

        btnAgregar.setBackground(new java.awt.Color(255, 166, 43));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(39, 71, 125));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestor de Turnos");

        lblHoraInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHoraInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblHoraInicio.setText("Hora Inicio");

        btnModificar.setBackground(new java.awt.Color(255, 166, 43));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(39, 71, 125));
        btnModificar.setText("Modificar");

        lblHoraFin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHoraFin.setForeground(new java.awt.Color(255, 255, 255));
        lblHoraFin.setText("Hora Fin");

        lblDias.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDias.setForeground(new java.awt.Color(255, 255, 255));
        lblDias.setText("Días:");

        chkLunes.setBackground(new java.awt.Color(39, 71, 125));
        chkLunes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkLunes.setForeground(new java.awt.Color(255, 255, 255));
        chkLunes.setText("Lunes");

        chkMiercoles.setBackground(new java.awt.Color(39, 71, 125));
        chkMiercoles.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkMiercoles.setForeground(new java.awt.Color(255, 255, 255));
        chkMiercoles.setText("Miércoles");
        chkMiercoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMiercolesActionPerformed(evt);
            }
        });

        chkMartes.setBackground(new java.awt.Color(39, 71, 125));
        chkMartes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkMartes.setForeground(new java.awt.Color(255, 255, 255));
        chkMartes.setText("Martes");

        chkJueves.setBackground(new java.awt.Color(39, 71, 125));
        chkJueves.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkJueves.setForeground(new java.awt.Color(255, 255, 255));
        chkJueves.setText("Jueves");

        chkViernes.setBackground(new java.awt.Color(39, 71, 125));
        chkViernes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkViernes.setForeground(new java.awt.Color(255, 255, 255));
        chkViernes.setText("Viernes");

        chkSabado.setBackground(new java.awt.Color(39, 71, 125));
        chkSabado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkSabado.setForeground(new java.awt.Color(255, 255, 255));
        chkSabado.setText("Sábado");

        chkDomingo.setBackground(new java.awt.Color(39, 71, 125));
        chkDomingo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkDomingo.setForeground(new java.awt.Color(255, 255, 255));
        chkDomingo.setText("Domingo");

        btnColor.setBackground(new java.awt.Color(255, 166, 43));
        btnColor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnColor.setForeground(new java.awt.Color(39, 71, 125));
        btnColor.setText("Agregar Color");
        btnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFormularioTurnoLayout = new javax.swing.GroupLayout(pnlFormularioTurno);
        pnlFormularioTurno.setLayout(pnlFormularioTurnoLayout);
        pnlFormularioTurnoLayout.setHorizontalGroup(
            pnlFormularioTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormularioTurnoLayout.createSequentialGroup()
                .addGroup(pnlFormularioTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFormularioTurnoLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblNombre)
                        .addGroup(pnlFormularioTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFormularioTurnoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormularioTurnoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))))
                    .addGroup(pnlFormularioTurnoLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(pnlFormularioTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDias, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFormularioTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFormularioTurnoLayout.createSequentialGroup()
                                .addComponent(btnModificar)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregar))
                            .addGroup(pnlFormularioTurnoLayout.createSequentialGroup()
                                .addGroup(pnlFormularioTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlFormularioTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(chkLunes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(chkMiercoles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(chkViernes, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(chkDomingo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlFormularioTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlFormularioTurnoLayout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addGroup(pnlFormularioTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(chkJueves, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(chkMartes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(chkSabado, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))
                                    .addGroup(pnlFormularioTurnoLayout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(btnColor))))
                            .addGroup(pnlFormularioTurnoLayout.createSequentialGroup()
                                .addComponent(spnHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pnlFormularioTurnoLayout.setVerticalGroup(
            pnlFormularioTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioTurnoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(24, 24, 24)
                .addGroup(pnlFormularioTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraInicio)
                    .addComponent(spnHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoraFin)
                    .addComponent(spnHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDias)
                    .addComponent(chkLunes)
                    .addComponent(chkMartes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormularioTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMiercoles)
                    .addComponent(chkJueves))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormularioTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSabado)
                    .addComponent(chkViernes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormularioTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDomingo)
                    .addComponent(btnColor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(pnlFormularioTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnModificar))
                .addGap(26, 26, 26))
        );

        btnRegresar.setBackground(new java.awt.Color(224, 30, 72));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");

        javax.swing.GroupLayout pnlGestionTurnoLayout = new javax.swing.GroupLayout(pnlGestionTurno);
        pnlGestionTurno.setLayout(pnlGestionTurnoLayout);
        pnlGestionTurnoLayout.setHorizontalGroup(
            pnlGestionTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGestionTurnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFormularioTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlGestionTurnoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlGestionTurnoLayout.setVerticalGroup(
            pnlGestionTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGestionTurnoLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(18, 18, 18)
                .addGroup(pnlGestionTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pnlFormularioTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGestionTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGestionTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkMiercolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMiercolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMiercolesActionPerformed

    /**
     * Acción realizada al presionar el botón agregar;
     * Agrega un nuevo turno con la configuración del formulario a la tabla
     * @param evt click al botón agregar
     */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombre = txtNombre.getText();
        LocalTime[] horas = getHoras();
        Set<DayOfWeek> dias = getDias();
        Color color;
        
        if (this.colorTurno == null) {
            colorTurno = Color.GRAY;
        }
        
        DTOTurno turno = new DTOTurno(nombre, horas[0], horas[1], dias, colorTurno);
        
        //todo
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * Permite al usuario seleccionar un color preferido para el turno que va a 
     * crear en caso de que así lo desee. De lo contrario, el turno se agrega con
     * un color gris.
     * @param evt click al boton de agregar color
     */
    private void btnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorActionPerformed
        Color colorSeleccionado = JColorChooser.showDialog(
            null,                   
            "Selecciona un Color",  
            Color.GRAY               
        );

        if (colorSeleccionado != null) {
            this.colorTurno = colorSeleccionado;
        }
    }//GEN-LAST:event_btnColorActionPerformed

    /**
     * Método que configura los spinners al iniciar la interfaz
     */
    public void configurarSpinners(){
        SpinnerDateModel modeloInicio = new SpinnerDateModel();
        SpinnerDateModel modeloFin = new SpinnerDateModel();
        spnHoraInicio.setModel(modeloInicio);
        spnHoraFin.setModel(modeloFin);
        
        JSpinner.DateEditor editarHoraInicio = new JSpinner.DateEditor(spnHoraInicio, "HH:mm");
        JSpinner.DateEditor editarHoraFin = new JSpinner.DateEditor(spnHoraFin, "HH:mm");
        spnHoraInicio.setEditor(editarHoraInicio);
        spnHoraFin.setEditor(editarHoraFin);
    }
    
    public void configurarTabla(){
        String[] columnas = {"Nombre", "Inicio", "Fin", "Días", "Color"};
        modeloTabla.setColumnIdentifiers(columnas);
        tablaTurnosDisponibles.setModel(modeloTabla);
        
    }
    
    /**
     * Método que configura el mapa de días al iniciar la interfaz
     */
    public void configurarDias(){
        mapaDias.put(chkLunes, DayOfWeek.MONDAY);
        mapaDias.put(chkMartes, DayOfWeek.TUESDAY);
        mapaDias.put(chkMiercoles, DayOfWeek.WEDNESDAY);
        mapaDias.put(chkJueves, DayOfWeek.THURSDAY);
        mapaDias.put(chkViernes, DayOfWeek.FRIDAY);
        mapaDias.put(chkSabado, DayOfWeek.SATURDAY);
        mapaDias.put(chkDomingo, DayOfWeek.SUNDAY);
    }
    
    /**
     * Método que obtiene las horas ajustadas por el usuario
     * @return Set LocalTime con la hora de inicio y la hora de fin
     */
    public LocalTime[] getHoras(){
        Date fechaHoraInicio = (Date) spnHoraInicio.getValue();
        Date fechaHoraFin = (Date) spnHoraFin.getValue();
        LocalTime horaInicio = fechaHoraInicio.toInstant().atZone(ZoneId.systemDefault()).toLocalTime();
        LocalTime horaFin = fechaHoraFin.toInstant().atZone(ZoneId.systemDefault()).toLocalTime();
        if (!horaInicio.isBefore(horaFin)) {
            JOptionPane.showMessageDialog(this, "La hora de fin debe ser mayor a la de inicio", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        LocalTime[] horas = {horaInicio,horaFin};
        return horas;
    }
    
    /**
     * Método que filtra y obtiene los días seleccionados utilizando stream en el hashMap de 
     * los días de la semana
     * @return un Set tipo DaysOfWeek con los días que el usuario seleccionó
     */
    public Set<DayOfWeek> getDias(){
        return mapaDias.entrySet().stream()
            .filter(entry -> entry.getKey().isSelected())
            .map(Map.Entry::getValue)
            .collect(Collectors.toCollection(LinkedHashSet::new));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnColor;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JCheckBox chkDomingo;
    private javax.swing.JCheckBox chkJueves;
    private javax.swing.JCheckBox chkLunes;
    private javax.swing.JCheckBox chkMartes;
    private javax.swing.JCheckBox chkMiercoles;
    private javax.swing.JCheckBox chkSabado;
    private javax.swing.JCheckBox chkViernes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDias;
    private javax.swing.JLabel lblHoraFin;
    private javax.swing.JLabel lblHoraInicio;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel pnlFormularioTurno;
    private javax.swing.JPanel pnlGestionTurno;
    private javax.swing.JScrollPane pnlScroll;
    private javax.swing.JSpinner spnHoraFin;
    private javax.swing.JSpinner spnHoraInicio;
    private javax.swing.JTable tablaTurnosDisponibles;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
